backend/config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  
  resources :contacts
  resources :regions
  resources :levels
  resources :images
  resources :users
  resources :purchases
  resources :products
  
  controller :images do
    post 'images/upload' => :upload
    get 'images/*path' => redirect('images')
  end
  
  controller :products do
    post 'products/upload' => :upload
    get 'products/*path' => redirect('products')
  end
  
  controller :regions do
    post 'regions/upload' => :upload
    get 'regions/*path' => redirect('regions')
  end
  
  controller :contacts do
    post 'contacts/upload' => :upload
    get 'contacts/*path' => redirect('contacts')
  end
  
  controller :levels do
    post 'levels/upload' => :upload
    get 'levels/*path' => redirect('levels')
  end
  
  controller :recalls do
      get 'recalls/search' => :search
      post 'recalls/upload' => :upload
  end
  resources :recalls do
    member do
      get 'recalls/*path' => redirect('recalls')
    end
  end

  

end

backend/app/models/level.rb
class Level < ActiveRecord::Base
    has_many :recalls
    validates :display_name, presence: true, uniqueness: { case_sensitive: false }
    
    public
    def self.get_default()
        return 1
    end
end

backend/app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end
  
  # GET /levels/upload
  # for batch upload levels through json.
  def upload
    data = params[:json_data]
		levels = JSON.parse(data)
		levels.each do |level|
			@level = Level.find_by_id(level['id'])
			if @level.nil?
				@level = Level.create(:id => level['id'], :display_name => level['display_name'], :description => level['description'])
			end
		end
		
    respond_to do |format|
      format.html { redirect_to :controller => 'levels', :action => 'index' }
    end
    
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:display_name, :description)
    end
end

backend/app/helpers/levels_helper.rb
module LevelsHelper
end

backend/app/views/levels/_form.html.erb
<%= form_for(@level) do |f| %>
  <% if @level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% @level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :display_name %><br>
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/levels/_header.html.erb
<div class="jumbotron">
    <h1>Admin Panel - Recall Class</h1>
    <p>Online manipulation for Level Class data</p>
</div>

backend/app/views/levels/edit.html.erb
<h1>Editing Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

backend/app/views/levels/index.html.erb
<div class="container">
  <%= render 'header' %>
  <p id="notice"><%= notice %></p>
  
  <h1>Listing Recall Levels</h1>
  
  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>Display Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @levels.each do |level| %>
        <tr>
          <td><%= level.id %></td>
          <td><%= level.display_name %></td>
          <td><%= level.description %></td>
          <td><%= link_to 'Show', level %></td>
          <td><%= link_to 'Edit', edit_level_path(level) %></td>
          <td><%= link_to 'Destroy', level, method: :delete, 
            data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <a href="/levels/new" class="btn btn-default" role="button">New Recall Level</a></a>
  <br>
  <div>
      <h1>Batch Upload</h1>
      <%= form_tag("/levels/upload", method: "post", class: "form-horizontal") do %>
          <div class="form-group">
              <div class="col-sm-10">
                <%= text_area_tag :json_data, nil, :required => true, 
                :rows => 10, :class => "form-control",
                :placeholder => "[\n\t{\n\t\t\"id\": 1,\n\t\t 
                \"display_name\": \"Class I recall \",\n\t\t
                \"description\": \" a situation in which there is a reasonable probability that the use of or exposure to a violative product will cause serious adverse health consequences or death\"\n\t}\n]"%>
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-10">
                  <%= submit_tag("Upload", :class => "btn btn-default" ) %>
              </div>
          </div>
      <% end %>
  </div>
</div>

backend/app/views/levels/new.html.erb
<h1>New Level</h1>

<%= render 'form' %>

<%= link_to 'Back', levels_path %>

backend/app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Display name:</strong>
  <%= @level.display_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @level.description %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>