backend/config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  
  resources :contacts
  resources :regions
  resources :levels
  resources :images
  resources :users
  resources :purchases
  resources :products
  
  controller :images do
    post 'images/upload' => :upload
    get 'images/*path' => redirect('images')
  end
  
  controller :products do
    post 'products/upload' => :upload
    get 'products/*path' => redirect('products')
  end
  
  controller :regions do
    post 'regions/upload' => :upload
    get 'regions/*path' => redirect('regions')
  end
  
  controller :contacts do
    post 'contacts/upload' => :upload
    get 'contacts/*path' => redirect('contacts')
  end
  
  controller :levels do
    post 'levels/upload' => :upload
    get 'levels/*path' => redirect('levels')
  end
  
  controller :recalls do
      get 'recalls/search' => :search
      post 'recalls/upload' => :upload
  end
  resources :recalls do
    member do
      get 'recalls/*path' => redirect('recalls')
    end
  end

  

end

backend/app/models/image.rb
class Image < ActiveRecord::Base
    validates :filename, presence: true
    validates :category, presence: true, numericality: { only_integer: true }
    
    public
    def self.get_default()
        return 1
    end
    
    def as_json(options={})
        super(:except => [:created_at, :updated_at])

  end
end

backend/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    
    @image = Image.find_by_id(params[:id])
       
    
    respond_to do |format|
      format.html {  }
      format.json {  render json: @image }
    end
    
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end
  
  # GET /images/upload
  # for batch upload images through json.
  def upload
    data = params[:json_data]
		images = JSON.parse(data)
		images.each do |image|
			@image = Image.find_by_id(image['id'])
			if @image.nil?
				@image = Image.create(:id => image['id'], :description => image['description'], :filename => image['filename'], :category => image['category'])
			end
		end
		
    respond_to do |format|
      format.html { redirect_to :controller => 'images', :action => 'index' }
    end
    
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:category, :filename, :description)
    end
end

backend/app/helpers/images_helper.rb
module ImagesHelper
end

backend/app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <label for="category">Category</label>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon3">@</span>
    <%= f.text_field :category, class: "form-control" %>
  </div>
  

  <label for="filename">Filename</label>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon3">@</span>
    <%= f.text_field :filename, class: "form-control", placeholder: "example.jpg" %>
  </div>
  
  <label for="description">Description</label>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon3">@</span>
    <%= f.text_field :description, class: "form-control", placeholder: "just a test image" %>
  </div>
  
  <%= f.submit 'Confirm', :class => 'btn btn-primary spacer' %>
  
<% end %>

backend/app/views/images/_header.html.erb
<div class="jumbotron">
    <h1>Admin Panel - Images</h1>
    <p>Online manipulation for image data</p>
</div>

backend/app/views/images/edit.html.erb
<div class="container">

  <%= render 'header' %>
  <span class="label label-danger">Edit</span>
  <p id="notice"><%= notice %></p>
  
  <%= render 'form' %>
  
  <%= link_to 'Show', @image, :class => 'btn btn-primary spacer' %>
  <%= link_to 'Back', images_path, :class => 'btn btn-primary spacer' %>

</div>

backend/app/views/images/index.html.erb
<div class="container">
  
    <%= render 'header' %>
    
    <p id="notice"><%= notice %></p>
    
    <div>
      <h1>Listing Images</h1>
      <table class="table">
        <thead>
          <tr>
            <th>id</th>
            <th>Filename</th>
            <th>Description</th>
            <th>Category</th>
            <th colspan="4"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @images.each do |image| %>
            <tr>
              <td><%= image.id %></td>
              <td><%= image.filename %></td>
              <td><%= image.description %></td>
              <td><%= image.category %></td>
              <td><%= link_to 'Show', image %></td>
              <td><%= link_to 'Edit', edit_image_path(image) %></td>
              <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <a href="/images/new" class="btn btn-default" role="button">New Image</a></a>

    <div>
        <h1>Batch Upload</h1>
        <%= form_tag("/images/upload", method: "post", class: "form-horizontal") do %>
            <div class="form-group">
                <div class="col-sm-10">
                  <%= text_area_tag :json_data, nil, :required => true, :rows => 10, :class => "form-control",
                  :placeholder => "[\n\t{\n\t\t\"id\": 1,\n\t\t \"description\": \"Baltimore in 1960s\",\n\t\t \"filename\": \"0001.jpg\",\n\t\t \"category\": 1
\t}\n]"%>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-10">
                    <%= submit_tag("Upload", :class => "btn btn-default" ) %>
                </div>
            </div>
        <% end %>
    </div>
</div>

backend/app/views/images/new.html.erb
<div class="container">

<%= render 'header' %>

<%= render 'form' %>

<%= link_to 'Back', images_path, :class => 'btn btn-primary spacer' %>


</div>

backend/app/views/images/show.html.erb
<div class="container">

  <%= render 'header' %>
  <p id="notice"><%= notice %></p>
  
  <div class="panel panel-default">
    <div class="panel-body">
       <img style="max-width:256px;max-height:256px;", src=<%= asset_path(@image.filename) %>>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Cateogry</h3>
    </div>
    <div class="panel-body">
       <%= @image.category %>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Filename</h3>
    </div>
    <div class="panel-body">
       <%= @image.filename %>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Description</h3>
    </div>
    <div class="panel-body">
       <%= @image.description %>
    </div>
  </div>
  
  <%= link_to 'Edit', edit_image_path(@image), :class => 'btn btn-primary spacer' %>
  <%= link_to 'Back', images_path, :class => 'btn btn-primary spacer' %>

</div>