backend/config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  
  resources :contacts
  resources :regions
  resources :levels
  resources :images
  resources :users
  resources :purchases
  resources :products
  
  controller :images do
    post 'images/upload' => :upload
    get 'images/*path' => redirect('images')
  end
  
  controller :products do
    post 'products/upload' => :upload
    get 'products/*path' => redirect('products')
  end
  
  controller :regions do
    post 'regions/upload' => :upload
    get 'regions/*path' => redirect('regions')
  end
  
  controller :contacts do
    post 'contacts/upload' => :upload
    get 'contacts/*path' => redirect('contacts')
  end
  
  controller :levels do
    post 'levels/upload' => :upload
    get 'levels/*path' => redirect('levels')
  end
  
  controller :recalls do
      get 'recalls/search' => :search
      post 'recalls/upload' => :upload
  end
  resources :recalls do
    member do
      get 'recalls/*path' => redirect('recalls')
    end
  end

  

end

backend/app/models/recall.rb
class Recall < ActiveRecord::Base
  belongs_to :product
  belongs_to :level
  belongs_to :region
  has_one :contact
  
  validates :product, presence: true
  validates :level, presence: true
  validates :region, presence: true
  validates :date, presence: true
  
  before_save :level_verify, :region_verify
  
  public
  
  def self.recalls_by_upc_code(upc_code)
    Recall.joins(:product).where("recalls.product_id = products.id and products.upc_code = ?", upc_code).order("recalls.date DESC").select('recalls.*')
  end
  
  def as_json(options={})
    super(:except => [:created_at, :updated_at],
          :include => {
            :product => { :except => [:created_at, :updated_at],
                          :methods => [:image] 
            }
          }
    )

  end

  private
  
  def level_verify
    if self.level_id.nil? || Level.find_by_id(level_id).nil?
      self.level_id = Level.get_default()
    end
  end
  
  def region_verify
    if self.region_id.nil? || Region.find_by_id(region_id).nil?
      self.region_id = Region.get_default()
    end
  end
  
end

backend/app/controllers/recalls_controller.rb
class RecallsController < ApplicationController
  before_action :set_recall, only: [:show, :edit, :update, :destroy]

  # GET /recalls
  # GET /recalls.json
  def index
    @recalls = Recall.all
  end

  # GET /recalls/1
  # GET /recalls/1.json
  def show
  end

  # GET /recalls/new
  def new
    @recall = Recall.new
  end
  
  # GET /recalls/upload
  # for batch upload recalls through json.
  def upload
    data = params[:json_data]
		recalls = JSON.parse(data)
		recalls.each do |recall|
			@recall = Recall.find_by_id(recall['id'])
			if @recall.nil?
				@recall = Recall.create(:id => recall['id'], :product_id => recall['product_id'], :reason => recall['reason'], :level_id => recall['level_id'], :region_id => recall['region_id'], :contact_id => recall['contact_id'], :date => recall['date'])
			end
		end
		
    respond_to do |format|
      format.html { redirect_to :controller => 'recalls', :action => 'index' }
    end
    
  end
  
  # GET /recalls/search?upc_code=...
  def search
    if params.include?(:upc_code)
      @upc_code = params[:upc_code]
      @recalls = Recall.recalls_by_upc_code(params[:upc_code])
      @json = { :recalls => @recalls.as_json }
    else
      @json = { :recalls => [] }
    end
    
    respond_to do |format|
        format.html { render :index, status: :ok }
        format.json { render json:  @json }
    end
  end

  # GET /recalls/1/edit
  def edit
  end

  # POST /recalls
  # POST /recalls.json
  def create
    @recall = Recall.new(recall_params)

    respond_to do |format|
      if @recall.save
        format.html { redirect_to @recall, notice: 'Recall was successfully created.' }
        format.json { render :show, status: :created, location: @recall }
      else
        format.html { render :new }
        format.json { render json: @recall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recalls/1
  # PATCH/PUT /recalls/1.json
  def update
    respond_to do |format|
      if @recall.update(recall_params)
        format.html { redirect_to @recall, notice: 'Recall was successfully updated.' }
        format.json { render :show, status: :ok, location: @recall }
      else
        format.html { render :edit }
        format.json { render json: @recall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recalls/1
  # DELETE /recalls/1.json
  def destroy
    @recall.destroy
    respond_to do |format|
      format.html { redirect_to recalls_url, notice: 'Recall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recall
      @recall = Recall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recall_params
      params.require(:recall).permit(:product_id, :reason, :level_id, :region_id, :contact_id, :date)
    end
end

backend/app/helpers/recalls_helper.rb
module RecallsHelper
end

backend/app/views/recalls/_form.html.erb
<%= form_for(@recall) do |f| %>
  <% if @recall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recall.errors.count, "error") %> prohibited this recall from being saved:</h2>

      <ul>
      <% @recall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <label for="product_id">Product id</label>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon3">@</span>
    <%= f.text_field :product_id, class: "form-control", placeholder: 1 %>
  </div>
  

  <label for="filename">Reason</label>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon3">@</span>
    <%= f.text_field :reason, class: "form-control", placeholder: "illegal addictive." %>
  </div>
  
  <label for="description">Level id</label>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon3">@</span>
    <%= f.text_field :level_id, class: "form-control", placeholder: 1 %>
  </div>
  
  <label for="description">Region id</label>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon3">@</span>
    <%= f.text_field :region_id, class: "form-control", placeholder: 1 %>
  </div>
  
    <label for="description">Contact id</label>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon3">@</span>
    <%= f.text_field :contact_id, class: "form-control", placeholder: 1 %>
  </div>
  
  <label for="description">date</label>
  <div class="input-group">
    <%= f.datetime_select :date, class: "form-control", placeholder: "2016-10-23 05:56:00 UTC" %>
  </div>
  
  <%= f.submit 'Confirm', :class => 'btn btn-primary spacer' %>
  
<% end %>

backend/app/views/recalls/_header.html.erb
<div class="jumbotron">
    <h1>Admin Panel - Recall</h1>
    <p>Online manipulation for Recall data</p>
</div>

backend/app/views/recalls/edit.html.erb
<div class="container">

  <%= render 'header' %>
  <span class="label label-danger">Edit</span>
  <p id="notice"><%= notice %></p>
  
  <%= render 'form' %>
  
  <%= link_to 'Show', @recall, :class => 'btn btn-primary spacer' %>
  <%= link_to 'Back', recalls_path, :class => 'btn btn-primary spacer' %>

</div>

backend/app/views/recalls/index.html.erb
<div class="container">
  
  <%= render 'header' %>
  
  <p id="notice"><%= notice %></p>
  
  <div>
    <h1>Listing Recalls</h1>
    
    <% if !@upc_code.nil? %>
        <span class="label label-danger"> upc_code= <%= @upc_code %> </span>
    <% end %>  
  
    <table class="table">
      <thead>
        <tr>
          <th>id</th>
          <th>Product</th>
          <th>Reason</th>
          <th>Level</th>
          <th>Region</th>
          <th>Contact</th>
          <th>Date</th>
          <th colspan="7"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @recalls.each do |recall| %>
          <tr>
            <td><%= recall.id %></td>
            <td><%= link_to recall.product.name, recall.product %></td>
            <td><%= recall.reason %></td>
            <td><%= link_to recall.level.display_name, recall.level %></td>
            <td><%= link_to recall.region.display_name, recall.region %></td>
            <td>
              <%= 
                if !Contact.find_by_id(recall.contact_id) .nil?
                  link_to "Contacts", Contact.find_by_id(recall.contact_id)
                else
                  raw("no_contacts")
                end
              %>  
            </td>
            <td><%= recall.date %></td>
            <td><%= link_to 'Show', recall %></td>
            <td><%= link_to 'Edit', edit_recall_path(recall) %></td>
            <td><%= link_to 'Destroy', recall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <a href="/recalls/new" class="btn btn-default" role="button">New Recall</a></a>

  <div>
      <h1>Batch Upload</h1>
      <%= form_tag("/recalls/upload", method: "post", class: "form-horizontal") do %>
          <div class="form-group">
              <div class="col-sm-10">
                <%= text_area_tag :json_data, nil, :required => true, 
                :rows => 10, :class => "form-control",
                :placeholder => "[\n\t{\n\t\t\"id\": 1,\n\t\t 
                \"product_id\": 1,\n\t\t
                \"reason\": unidentified sources.\n\t\t
                \"level_id\": 1,\n\t\t
                \"region_id\": 1,\n\t\t
                \"contact_id\": 1,\n\t\t
                \"date\": \"October 17, 2016\"\n\t}\n]"%>
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-10">
                  <%= submit_tag("Upload", :class => "btn btn-default" ) %>
              </div>
          </div>
      <% end %>
  </div>
</div>

backend/app/views/recalls/new.html.erb
<h1>New Recall</h1>

<%= render 'form' %>

<%= link_to 'Back', recalls_path, :class => 'btn btn-primary spacer' %>

backend/app/views/recalls/show.html.erb
<div class="container">

  <%= render 'header' %>
  <p id="notice"><%= notice %></p>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Product</h3>
    </div>
    <div class="panel-body">
      <%= link_to @recall.product.name, @recall.product %>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Reason</h3>
    </div>
    <div class="panel-body">
       <%= @recall.reason %>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Level</h3>
    </div>
    <div class="panel-body">
       <%= link_to @recall.level.display_name, @recall.level %>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Region</h3>
    </div>
    <div class="panel-body">
      <%= link_to @recall.region.display_name, @recall.region %>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Contact</h3>
    </div>
    <div class="panel-body">
      <%= 
        if !Contact.find_by_id(@recall.contact_id) .nil?
          link_to "Contacts", Contact.find_by_id(@recall.contact_id)
        else
          raw("no_contacts")
        end
      %>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Date</h3>
    </div>
    <div class="panel-body">
       <%= @recall.date %>
    </div>
  </div>
  
  <%= link_to 'Edit', edit_recall_path(@recall), :class => 'btn btn-primary spacer' %>
  <%= link_to 'Back', recalls_path, :class => 'btn btn-primary spacer' %>

</div>